In [27]:
# задача 1
import numpy as np

vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [28]:
# задача 2
vector = np.arange(10,49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [29]:
# задача 3
vector = np.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
# задача 4
vector = np.zeros((8,8), dtype=int)
vector[1::2,::2] = 1
vector[::2,1::2] = 1
print(vector)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
# задача 5
vector = np.zeros((5,5))
vector += np.arange(5)
print(vector)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [32]:
# задача 6
vector = np.ones((7,7))
vector[1:-1,1:-1] = 0
print(vector)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [33]:
# задача 7, 1 способ
vector = np.arange(15)
vector[(3 < vector) & (vector <= 8)] *= -1
print(vector)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


In [36]:
# задача 7, 2 способ
vector1 = np.arange(15)
for i in vector1:
    vector1[(3 < vector1) & (vector1 <= 8)] *= -1
print(vector1)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


In [21]:
# задача 8
vector = np.random.randint(0,5,(5,14))
print((~vector.any(axis=0)).any())

False
